#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get install -y haproxy=2.8.\*
sudo echo -e "frontend\n\
     bind *:80\n\
     mode http\n\
     default_backend servers_hol\n\n\
backend servers_hol\n\
        balance roundrobin\n\
        mode http\n\
        server 99750-web-01 54.87.171.36:80\n\
        server 99750-web-02 34.203.38.116:80" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
if [ "$(pgrep -c haproxy)" -le 0 ]; then
    sudo service haproxy start
else
    sudo service haproxy restart
fi
