#!/usr/bin/env bash
# backing up and compressing mysql data
password="$1"
timestamp=$(date +'%d-%m-%Y')
sudo sudo mysqldump -uroot -p"$password" --all-databases > backup.sql
tar -cvzf "$timestand.tar.gz" backup.sql
