#!/usr/bin/env bash
#setting ufw on firewall

sudo apt install ufw
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow htpps
sudo ufw enable
sudo ufw status
