#!/usr/bin/env bash
#Accessing current user

# Check if an argument is provided
if [ $# -ne 1 ]; then
    echo "Usage: $0 <username>"
    exit 1
fi

# Get the username from the command line argument
username="$1"

# Run the 'whoami' command as the specified user using 'sudo'
sudo -u "$username" whoami
