#!/bin/env bash
NGINX_USER_ID=1000
NGINX_GROUP_ID=1000
chown $NGINX_USER_ID:$NGINX_GROUP_ID /var/run/nginx /etc/nginx /var/log/nginx
sed -i -e "s/user .*/user $NGINX_USER_ID/" -e "s/group .*/group $NGINX_GROUP_ID/" /etc/nginx/nginx.conf
service nginx start
sed -i "s/listen 80;/listen 8080 default_server/" /etc/nginx/conf.d/default.conf
